import { jsPDF } from "jspdf";
import EPub from "epub-gen";
import { slugify } from "./editor-utils";

function downloadBlob(blob: Blob, filename: string, type: string) {
  const url = URL.createObjectURL(new Blob([blob], { type }));
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function htmlToPlainText(html: string): string {
  const element = document.createElement("div");
  element.innerHTML = html;
  return element.textContent?.replace(/\s+/g, " ").trim() || "";
}

function createTextBlocks(html: string): string[] {
  if (!html.trim()) {
    return [];
  }

  const element = document.createElement("div");
  element.innerHTML = html;

  const blocks = Array.from(
    element.querySelectorAll("h1, h2, h3, p, li, blockquote"),
  )
    .map((node) => node.textContent?.replace(/\s+/g, " ").trim())
    .filter(Boolean);

  return blocks.length ? blocks : [htmlToPlainText(html)];
}

function toBlob(result: unknown): Blob {
  if (result instanceof Blob) {
    return result;
  }

  if (result instanceof ArrayBuffer) {
    return new Blob([result], { type: "application/epub+zip" });
  }

  const maybeBuffer = result as { type?: string; data?: number[] };

  if (maybeBuffer?.type === "Buffer" && Array.isArray(maybeBuffer.data)) {
    return new Blob([Uint8Array.from(maybeBuffer.data)], {
      type: "application/epub+zip",
    });
  }

  if (typeof result === "string") {
    return new Blob([result], { type: "application/epub+zip" });
  }

  return new Blob([String(result)], { type: "application/epub+zip" });
}

/**
 * Export HTML content as a print-ready PDF.
 */
export async function exportAsPdf(title: string, html: string): Promise<void> {
  const safeTitle = title.trim() || "Untitled document";
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
    compress: true,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 54;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;
  let pageNumber = 1;

  const addPageNumber = () => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(String(pageNumber), pageWidth / 2, pageHeight - 30);
    pageNumber += 1;
  };

  const addTextBlock = (
    text: string,
    fontSize: number,
    leading: number,
    isHeading = false,
  ) => {
    const lines = doc.splitTextToSize(text, contentWidth);

    if (y + lines.length * leading > pageHeight - margin) {
      addPageNumber();
      doc.addPage();
      y = margin;
    }

    doc.setFont("helvetica", isHeading ? "bold" : "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(20, 20, 20);
    doc.text(lines, margin, y);
    y += lines.length * leading + 10;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(15, 23, 42);
  doc.text(safeTitle, margin, 92);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(70, 70, 70);
  doc.text("Generated by AI Writing Assistant", margin, 118);

  y = 158;

  const blocks = createTextBlocks(html);

  if (!blocks.length) {
    addTextBlock("This document is empty.", 12, 17);
  }

  blocks.forEach((block) => {
    const isHeading = /^Chapter\s+\d+/i.test(block) || block.length < 70;
    addTextBlock(block, isHeading ? 15 : 11, isHeading ? 21 : 17, isHeading);
  });

  addPageNumber();
  doc.save(`${slugify(safeTitle)}.pdf`);
}

/**
 * Export plain text or HTML content as an EPUB file.
 */
export async function exportAsEpub(title: string, text: string): Promise<void> {
  const safeTitle = title.trim() || "Untitled document";
  const data = text.replace(/\n/g, "<br />");

  const options = {
    title: safeTitle,
    author: "Generated by AI Writing Assistant",
    lang: "en",
    content: [
      {
        title: safeTitle,
        data,
      },
    ],
  };

  const epubBlob = await new Promise<Blob>((resolve, reject) => {
    new EPub(options, (err: any, result: any) => {
      if (err) {
        reject(err);
        return;
      }

      resolve(toBlob(result));
    });
  });

  downloadBlob(epubBlob, `${slugify(safeTitle)}.epub`, "application/epub+zip");
}