import { jsPDF } from "jspdf";
import { saveAs } from "file-saver";
import JSZip from "jszip";

/**
 * Export HTML content as a print-ready PDF.
 * Uses jsPDF to render the raw HTML (basic styling).
 */
export async function exportAsPdf(title: string, html: string): Promise<void> {
  const doc = new jsPDF("p", "pt", "a4");
  // Simple conversion: add title and raw HTML as text.
  // For richer layout you could use html2canvas + addImage, but this keeps it lightweight.
  doc.setFontSize(18);
  doc.text(title, 40, 50);
  doc.setFontSize(12);
  const lines = doc.splitTextToSize(html.replace(/<[^>]+>/g, " "), 515);
  doc.text(lines, 40, 80);
  doc.save(`${title}.pdf`);
}

/**
 * Export plain-text content as an EPUB file.
 * Uses JSZip to create a minimal EPUB with a single chapter.
 */
export async function exportAsEpub(title: string, text: string): Promise<void> {
  // Generate a simple UUID for the EPUB
  const uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });

  // Convert text to simple HTML (wrap lines in <p> tags)
  const paragraphs = text.split('\n\n').map(p => `<p>${p.trim()}</p>`).join('\n');
  const contentHtml = `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>${title}</title>
  </head>
  <body>
    ${paragraphs}
  </body>
</html>`;

  // EPUB 2.0 files
  const mimetype = "application/epub+zip";
  const containerXml = `<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`;
  const contentOpf = `<?xml version="1.0"?>
<package version="2.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="uid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:title>${title}</dc:title>
    <dc:creator>Generated by AI Writing Assistant</dc:creator>
    <dc:date>${new Date().toISOString()}</dc:date>
    <dc:identifier id="uid">urn:uuid:${uuid}</dc:identifier>
  </metadata>
  <manifest>
    <item id="toc" media-type="application/x-dtbncx+xml" href="toc.ncx"/>
    <item id="chapter" media-type="application/xhtml+xml" href="chapter001.xhtml"/>
  </manifest>
  <spine>
    <itemref idref="chapter"/>
  </spine>
</package>`;
  const tocNcx = `<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="${uuid}"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle>
    <text>${title}</text>
  </docTitle>
  <navMap>
    <navPoint id="navpoint-1" playOrder="1">
      <navLabel>
        <text>Chapter 1</text>
      </navLabel>
      <content src="chapter001.xhtml"/>
    </navPoint>
  </navMap>
</ncx>`;

  // Create ZIP file with JSZip
  const zip = new JSZip();
  // mimetype must be first and uncompressed
  zip.file("mimetype", mimetype, { binary: true });
  zip.file("META-INF/container.xml", containerXml);
  const ops = zip.folder("OEBPS");
  ops?.file("content.opf", contentOpf);
  ops?.file("toc.ncx", tocNcx);
  ops?.file("chapter001.xhtml", contentHtml);

  // Generate EPUB blob
  const epubBlob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  saveAs(epubBlob, `${title}.epub`);
}