import { jsPDF } from "jspdf";
import { saveAs } from "file-saver";
import EPub from "epub-gen";

/**
 * Export HTML content as a print‑ready PDF.
 * Uses jsPDF to render the raw HTML (basic styling).
 */
export async function exportAsPdf(title: string, html: string): Promise<void> {
  const doc = new jsPDF("p", "pt", "a4");
  // Simple conversion: add title and raw HTML as text.
  // For richer layout you could use html2canvas + addImage, but this keeps it lightweight.
  doc.setFontSize(18);
  doc.text(title, 40, 50);
  doc.setFontSize(12);
  const lines = doc.splitTextToSize(html.replace(/<[^>]+>/g, " "), 515);
  doc.text(lines, 40, 80);
  doc.save(`${title}.pdf`);
}

/**
 * Export plain‑text content as an EPUB file.
 * Uses epub-gen to create a minimal EPUB with a single chapter.
 */
export async function exportAsEpub(title: string, text: string): Promise<void> {
  const options = {
    title,
    author: "Generated by AI Writing Assistant",
    content: [
      {
        title: "Chapter 1",
        data: text.replace(/\n/g, "<br/>"),
      },
    ],
  };

  // epub-gen writes a Blob; we use file-saver to trigger download.
  const epubBlob = await new Promise<Blob>((resolve, reject) => {
    // @ts-ignore – epub-gen expects a callback
    new EPub(options, (err: any, result: any) => {
      if (err) reject(err);
      else resolve(result);
    });
  });

  saveAs(epubBlob, `${title}.epub`);
}